name: MacOS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-on-macos:
    runs-on: macos-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install required dependencies
      run: brew install check
    - name: Build project
      run: |
        cd src
        make
    - name: Run test
      run: |
        cd src
        make test
