name: String CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Check style
      uses: jidicula/clang-format-action
      with:
        clang-format-version: '16'
        check-path: 'src'
        fallback-style: '-style=file -assume-filename=materials/linters/.clang-format'

    - name: Build project
      run: |
        cd src
        make
