name: String CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Check style
      run: |
        cd src
        make lint-check

    - name: Build project
      run: |
        cd src
        make
