name: String CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Check style
      run: |
        brew install clang-format
        cd src
        OUTPUT=$(make lint-check)
        EXIT_CODE=$?
        if [[ $EXIT_CODE -eq 0 ]]; then
          echo "clang-format check passed: no style issues found"
        else
          echo "$OUTPUT"
          echo "::error::clang-format found style issues"
          exit 1
        fi

    - name: Build project
      run: |
        cd src
        make
