name: String CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  build-on-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Install required dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential cmake pkg-config git automake autoconf libtool pkg-config texinfo tetex-bin
    - name: Check
      uses: libcheck/check@latest
    - name: Build project
      run: |
        cd src
        make
    - name: Run test
      run: |
        cd src
        make test
