name: String CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-on-macos:

    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build project
      run: |
        cd src
        make

  build-on-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build project
      run: |
        cd src
        make
